<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-P7VKIKU" name="Test" tests="3" failures="2" timestamp="20 Apr 2018 18:24:35 GMT" time="3.987" errors="0">
  <testcase name="teste01" time="0.001" classname="teste.Testar">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at teste.Testar.teste01(Testar.java:31)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- teste01 -->
  <testcase name="teste02" time="0.0" classname="teste.Testar"/>
  <testcase name="teste03" time="0.0" classname="teste.Testar">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at teste.Testar.teste03(Testar.java:59)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- teste03 -->
</testsuite> <!-- Test -->
